# Generated by Django 3.2.9 on 2021-12-02 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='photos/products')),
                ('image2', models.ImageField(upload_to='photos/products')),
                ('image3', models.ImageField(upload_to='photos/products')),
                ('image4', models.ImageField(upload_to='photos/products')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.products')),
            ],
        ),
    ]
