# Generated by Django 3.2.9 on 2021-12-03 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='category_name',
            new_name='sub_category_name',
        ),
    ]
